/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Xavier Castejon
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altEntrenador = new javax.swing.JButton();
        altaPokemon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        altEntrenador.setText("Alta Entrenador");
        altEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altEntrenadorActionPerformed(evt);
            }
        });

        altaPokemon.setText("Alta Pokemon");
        altaPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPokemonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(altEntrenador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(altaPokemon)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altEntrenador)
                    .addComponent(altaPokemon))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altEntrenadorActionPerformed
        AltaEntrenador alt = new AltaEntrenador(this, true);
        alt.setLocationRelativeTo(null);
        alt.setVisible(true);

    }//GEN-LAST:event_altEntrenadorActionPerformed

    private void altaPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPokemonActionPerformed
        // TODO add your handling code here:
        AltaPokemon alt = new AltaPokemon(this, true);
        alt.setLocationRelativeTo(null);
        alt.setVisible(true);
        
    }//GEN-LAST:event_altaPokemonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altEntrenador;
    private javax.swing.JButton altaPokemon;
    // End of variables declaration//GEN-END:variables
}
